version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - npm install   # Install any dependencies
      - npm run build  # Replace with your build command (e.g., webpack, gulp, etc.)
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '*/'  # Include all files in the build directory
  base-directory: /path/to/your/source/code
