version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
  commands:
    - npm -g install npm@latest
    - npm install
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '*/'  # Include all files in the build directory
  base-directory: /path/to/your/source/code
